export const PASSWORD_RESET_TOKEN = 'PASSWORD_RESET_TOKEN';
export const EMAIL_VERIFY_TOKEN = 'EMAIL_VERIFY_TOKEN';
export const LOGIN_ACCESS_TOKEN = 'LOGIN_ACCESS_TOKEN';

export const LOGIN_REFRESH_TOKEN = 'LOGIN_REFRESH_TOKEN';
